### ISSUE TITLE
FontBakery  --  🔥 FAIL: Check if OS/2 xAvgCharWidth is correct

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/kreon#5]
## Fontbakery report

<details>
<summary><b>[1] Kreon-VF.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Check if OS/2 xAvgCharWidth is correct.</summary>

* [com.google.fonts/check/034](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/034)
* :fire: **FAIL** OS/2 xAvgCharWidth is 464 but it should be 446 which corresponds to the weighted average of the widths of the latin lowercase glyphs in the font

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 1 | 0 | 0 | 0 | 0 |
| 0% | 100% | 0% | 0% | 0% | 0% |

**Comment by eliheuer** [comment]
This is easy to fix with `fonttools`, so I might as well build it into `BUILD.py`.

**Comment by davelab6** [comment]
Don't bother :)
