### ISSUE TITLE
FontBakery -- ⚠️ WARN: Check if each glyph has the recommended amount of contours

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/kreon#7]
There are only three problem glyphs and I checked each one, example:

![screen shot 2018-10-24 at 2 34 30 pm](https://user-images.githubusercontent.com/5162664/47453331-7274e900-d79a-11e8-81a6-dd8a304febbd.png)

## Fontbakery report

<details>
<summary><b>[1] Kreon-VF.ttf</b></summary>
<details>
<summary>:warning: <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/153](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/153)
* :warning: **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: asterisk	Contours detected: 2	Expected: 1 or 4
Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: Eth	Contours detected: 3	Expected: 2

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 1 | 0 | 0 | 0 |
| 0% | 0% | 100% | 0% | 0% | 0% |

**Comment by eliheuer** [comment]
This is good.

**Comment by behdad** [comment]
How does this test work?  I'm curious.

**Comment by eliheuer** [comment]
@behdad FontBakery has a list of possible expected contour counts for each glyph. 

For example the glyph in the image above produced a warn because two contours is unusual for an `asterisk`.

@felipesanches would know more than I do.

**Comment by eliheuer** [comment]
Starts @ line 2545: https://github.com/googlefonts/fontbakery/blob/master/Lib/fontbakery/specifications/googlefonts.py

**Comment by felipesanches** [comment]
Marc Foley (@m4rc1e) created this check. It is based on statistics of typical amounts of contours for each glyph. Surely there can be glyphs that are perfectly fine but do not match the usual contour counts. The asterisk is clearly an example of that.

I think what Marc intends to catch with this check are not the outliners (like the asterisk above) but actually botched up glyphs. One classic example of a real problem that this would detect would be glyphs with 2 identical sets of outlines on top of each other, which would happen if a designer duplicated the curves during design work but then forgot to delete the copy before building the font binary.

**Comment by eliheuer** [comment]
Yeah, so I looked at all the glyphs reported and decided that there are no issues. I mainly made this issue so that the next person to work on this font understands that this has been looked at.

**Comment by felipesanches** [comment]
@graphicore, this is the kind of documentation of "warning overrides" that you have once suggested as part of the Dashboard workflow, right?

At the same time, perhaps we could save a `fontbakery.conf` file in the root of the font project repo to let the user specify these overrides and then subsequent runs of FontBakery would not emit these warnings.

**Comment by graphicore** [comment]
Yeah, this would be an example. A `fontbakery.conf` file could be a nice solution for these overrides.

**Comment by davelab6** [comment]
All WARN results can be ignored by default, no?

**Comment by felipesanches** [comment]
yes. The suggested feature described above was actually meant to also cover "error overrides".
